name: Debug NPM Authentication

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Debug Environment
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Registry: $(npm config get registry)"
          echo "NPM_TOKEN exists: $([[ -n "$NPM_TOKEN" ]] && echo "YES" || echo "NO")"
          echo "NODE_AUTH_TOKEN exists: $([[ -n "$NODE_AUTH_TOKEN" ]] && echo "YES" || echo "NO")"
          echo "NPM_TOKEN length: ${#NPM_TOKEN}"
          echo "NODE_AUTH_TOKEN length: ${#NODE_AUTH_TOKEN}"
          echo "NPM_TOKEN starts with: ${NPM_TOKEN:0:10}..."
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Test NPM Auth Method 1 (NODE_AUTH_TOKEN)
        run: |
          echo "Testing with NODE_AUTH_TOKEN..."
          npm whoami || echo "❌ NODE_AUTH_TOKEN failed"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Test NPM Auth Method 2 (Manual .npmrc)
        run: |
          echo "Testing with manual .npmrc..."
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          npm whoami || echo "❌ Manual .npmrc failed"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Test NPM Auth Method 3 (npm config)
        run: |
          echo "Testing with npm config..."
          npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
          npm whoami || echo "❌ npm config failed"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Check package info
        run: |
          echo "Package name: $(node -p "require('./package.json').name")"
          echo "Package version: $(node -p "require('./package.json').version")"
          npm view rag-cli-tester versions --json || echo "Package doesn't exist yet"
