name: Test and Build

on:
  # Run tests on pull requests
  pull_request:
    branches:
      - main
      - master
      
  # Run tests on pushes to main (but don't publish)
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '*.md'
      - '.github/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint --if-present
        
      - name: Run tests
        run: npm test --if-present
        
      - name: Build package
        run: npm run build
        
      - name: Test CLI installation
        run: |
          npm link
          rag-test --help || (echo "CLI test failed" && exit 1)
          npm unlink -g || true
